//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplified_School_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_package
    {
        public int API_packageId { get; set; }
        public string Package_name { get; set; }
        public string Package_description { get; set; }
        public string Package_url { get; set; }
        public int Package_callId { get; set; }
    
        public virtual Package_call Package_call { get; set; }
    }
}
