//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simplified_School_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestId { get; set; }
        public int Feature_requestId { get; set; }
        public int Info_requestId { get; set; }
    
        public virtual Feature_request Feature_request { get; set; }
        public virtual Info_request Info_request { get; set; }
    }
}
